float:
  angular:
  - base_args: ['@metric', '@dimension']
    constructor: ElasticsearchKNN
    disabled: false
    docker_tag: ann-benchmarks-elasticsearch
    module: ann_benchmarks.algorithms.elasticsearch
    name: elasticsearch
    run_groups:
      m-16-ef-128:
        arg_groups: [
          {ef_construction: 128, m: 16},
        ]
        args: {}
        query_args: [[8, 16, 32, 64, 128]]
  # euclidean:
  # - base_args: ['@metric', '@dimension']
  #   constructor: ElasticsearchKNN
  #   disabled: false
  #   docker_tag: ann-benchmarks-elasticsearch
  #   module: ann_benchmarks.algorithms.elasticsearch
  #   name: elasticsearch
  #   run_groups:
  #     m-16-ef-128:
  #       arg_groups: [{ef_construction: 128, m: 16}]
  #       args: {}
  #       query_args: [[8, 16, 32, 64, 128]]
