float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant
    run_groups:
      default:
        args: [
          ['none', 'binary'], #quantization
          [ 16], #m
          [ 128 ], #ef_construct
        ]
        query_args: [
          [8, 16, 32, 64, 128], #hnsw_ef
          [False], # re-score
        ]
